### ISSUE TITLE
Build failure for Gecode 6.1.0 on mips and mipsel architectures with gcc 8.2

### ISSUE THREAD

**Issue by kaol** [Gecode/gecode#34]
Building Gecode 6.1.0 fails on [mips](https://buildd.debian.org/status/fetch.php?pkg=gecode&arch=mips&ver=6.1.0-1&stamp=1540903224&raw=0) and [mipsel](https://buildd.debian.org/status/fetch.php?pkg=gecode&arch=mipsel&ver=6.1.0-1&stamp=1540907457&raw=0) arches on Debian. Gecode 6.0.1 built on both successfully.

gcc version had changed between the build attempts of Gecode releases. 6.0.1 got built with gcc 7.3 but 6.1.0 got built with gcc 8.2. I didn't yet try building 6.0.1 with a newer gcc version or 6.1.0 with the older one.

Both architectures saw the failure while running the test suite on the same test.

```
Search::PBS::SEB::DFS+LDS::Solve::3::1 ++
Search::PBS::SEB::DFS+LDS::Solve::3::2 ++
Search::PBS::SEB::DFS+LDS::Solve::3::3 ++
Search::PBS::SEB::DFS+LDS::Solve::3::4 ++
Search::PBS::SEB::DFS+LDS::Solve::3::5 ++
Search::PBS::SEB::DFS+LDS::Solve::3::6 ++
Search::PBS::SEB::DFS+LDS::Solve::3::7 Operating system error: Mutex::~Mutex[pthread_mutex_destroy]terminate called without an active exception
make[1]: *** [Makefile:1271: check] Aborted
```

This may well be some bug in gcc and/or some other dependency but I'd love to hear your thoughts before I explore this further.

**Comment by chschulte** [comment]
Hi,

That looks indeed strange. However, the reason why it shows up is because I changed which tests are run (I guess you use make check to run tests). I think I’ll cheat and change them in the develop branch…

Cheers
Christian

--
Christian Schulte, https://chschulte.github.io/
Professor of Computer Science
Software and  Computer Systems
School of Electrical Engineering and Computer Science
KTH Royal Institute of Technology, Sweden

**Comment by chschulte** [comment]
I just changed make check. So, under the carpet...
