### ISSUE TITLE
compilation error with Visual Studio 2015 and CMakeLists.txt

### ISSUE THREAD

**Issue by johnwspirent** [Gecode/gecode#50]
Hi, I am getting compilation errors using the Visual Studio 2015 compiler and the supplied CMakeLists.txt, e.g.:

1>C:\svn\gecode-release-6.2.0\gecode/kernel/branch/merit.hpp(193): error C2923: 'Gecode::VarBranch': 'Gecode::MeritFunction<View>::Var' is not a valid template type argument for parameter 'Var'
1>C:\svn\gecode-release-6.2.0\gecode/kernel/branch/merit.hpp(193): note: see declaration of 'Gecode::MeritFunction<View>::Var'

As you can see this is with gecode 6.2.0. I am actually using the MSVC 2017 IDE with the 2015 toolchain.

Do you support MSVC 2015? 
Regards
John

**Comment by chschulte** [comment]
Hi,

We did support it at some point in time. Let me have a look a little later, it is first day after holidays today…

Cheers
Christian

--
Christian Schulte, https://chschulte.github.io/
Professor of Computer Science
Software and Computer Systems
School of Electrical Engineering and Computer Science
KTH Royal Institute of Technology, Sweden

**Comment by chschulte** [comment]
Hi again, I just committed some fixes to the develop branch on GitHub so that it compiles again with MSVC 2015.

Cheers
Christian

--
Christian Schulte, https://chschulte.github.io/
Professor of Computer Science
Software and Computer Systems
School of Electrical Engineering and Computer Science
KTH Royal Institute of Technology, Sweden

**Comment by johnwspirent** [comment]
Hi, I can confirm it compiles for me as well. Many thanks for the quick response.
Regards
John
