### ISSUE TITLE
Inconsistence between gist search tree and search statistics

### ISSUE THREAD

**Issue by 95A31** [Gecode/gecode#59]
Hello,

I am working with the steelmillslab problem present in the minizinc-benchmarks. The nodes displayed by fzn-gecode-gist are more than what printed in the statistics from fzn-gecode for more than 1 solution.

To reproduce the problem is necessary:

1.  Create the FlatZinc:
      - [Model](https://raw.githubusercontent.com/MiniZinc/minizinc-benchmarks/master/steelmillslab/steelmillslab.mzn):  From minizinc-benchmarks.
      - [Data](https://raw.githubusercontent.com/MiniZinc/minizinc-benchmarks/master/steelmillslab/bench_13_0.dzn): From minizinc-benchmarks
      - Command: `minizinc --solver org.minizinc.globalizer -c steelmillslab.mzn bench_13_0.dzn -o steelmillslab13.fzn`

2. Launch GECODE:
    - Regular: `fzn-gecode -s -n 2 steelmillslab13.fzn`, 1550 nodes, 725 failure, 2 solutions.
    - Gist: `fzn-gecode-gist  steelmillslab13.fzn`, 824+729+2=1555 nodes, 729 failures, 2 solutions.

I am using Gecode 6.2.0 present in the MiniZinc distribution 2.3.2 both in Ubuntu 18.04 LTS and Manjaro.

**Comment by chschulte** [comment]
Hi,

This is indeed possible, the command line search has an additional optimization that Gist does not use, so the search apce might be slightly smaller.

This can happen due to recomputation for optimization problems, but the difference is normally small.

Cheers
Christian

--
Christian Schulte, https://chschulte.github.io/
Professor of Computer Science
Software and  Computer Systems
School of Electrical Engineering and Computer Science
KTH Royal Institute of Technology, Sweden
