### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [Gecode/gecode#64]
Would you like to wrap any pointer data members with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [CombinedStop](https://github.com/Gecode/gecode/blob/eea9480b8157e532bc44f4ced88f5fbda5220892/gecode/driver/script.hpp#L57)
- [CPProfilerSearchTracer](https://github.com/Gecode/gecode/blob/d8e4fa2e55c97de7cd75a7a05f80e84eacd7faec/gecode/search/cpprofiler/tracer.cpp#L54)

**Comment by zayenz** [comment]
In general I agree that it might be a good idea to update the Gecode APIs to use modern C++ wrappers for pointers to more clearly manage access rights, at least for the more user-facing parts. However, I think that would require a lot of work and careful planning to make it well-thought out, and that is too much work at this point unfortunately.

Until there is time to address this in a larger context for a new major version of Gecode, I will close this issue with wont-fix. Thanks for the pointer though :-)

**Comment by elfring** [comment]
I am curious under which circumstances the affected software components will be improved a bit more.

**Comment by zayenz** [comment]
Unfortunately, neither I nor my co-maintainer Guido has a lot of time. We've been slowly restarting maintenance and development of Gecode since the founder passed away in March (https://groups.google.com/g/gecode/c/1YM-JVChzZ4/m/9WEYqGkCBAAJ), but it takes some time. Currently, most of the time I personally put into Gecode is on trying to improve testing and general small fixes.

For the specific question in this issue, I think that introducing the usage of modern C++ pointers (while most likely a very good idea) is a larger issue than just the two candidates that you mentioned, and that it will require a larger effort.
